
```{r}
library(tidyverse)
library(tidymodels)
library(dplyr)
library(themis)
library(caret)
```


#===========================================
# Read and inspect data
#===========================================

```{r}
score <- read_csv('C:/Users/ASUS/Desktop/MATHia/student_scores_train.csv')
feature <- read_csv('C:/Users/ASUS/Desktop/MATHia/features.csv')
```

```{r}
ou <- score %>%
  dplyr::select("Anon.Student.Id","Post3Meta") %>%
  left_join(feature, by = "Anon.Student.Id")

```

# Round the Post3Meta
```{r}
table(ou$Post3Meta)

ou$Post3Meta <- round(ou$Post3Meta)

ou <- ou %>% drop_na(Post3Meta)

table(ou$Post3Meta)
```


# Convert Scores into Ordinal Categories
```{r}
ou <- ou %>%
  mutate(Post3Meta = case_when(
    Post3Meta %in% c(1, 2)  ~ 1,
    Post3Meta == 3          ~ 2,
    Post3Meta == 4          ~ 3,
    Post3Meta == 5          ~ 4,
    Post3Meta %in% c(6, 7)  ~ 5,
  )) %>%
  mutate(Post3Meta = factor(Post3Meta, levels = 1:5, ordered = TRUE))

# check the data 
ou$Post3Meta
table(ou$Post3Meta)

```



#===========================#
#     feature selection     #
#===========================#

```{r}
selected_features <- c(
  "Level2_Hints_Per_Problem",
  "aplse_score_ratio",
  "avg_hint_count",
  "avg_correct_attempt_per_problem",
  "avg_attempt_per_problem"
)
```

```{r}
ou <- ou %>%
  dplyr::select(Post3Meta, all_of(selected_features))
```


#===========================#
#     Train-Test Split      #
#===========================#

```{r}
set.seed(123)

ou_split<-initial_split(ou, strata = "Post3Meta")

ou_train<-training(ou_split)

ou_test<-testing(ou_split)
```


## Formula and Recipe

```{r}
rf_formula<-as.formula("Post3Meta ~ .")
```

```{r}
ou_rec <- recipe(rf_formula, data = ou_train) %>%
  update_role(Post3Meta, new_role = "outcome") %>%
  step_nzv(all_predictors()) %>%
  step_impute_knn(all_numeric_predictors()) %>%
  step_corr(all_numeric_predictors(), threshold = 0.95) %>%
  step_normalize(all_predictors())%>%
  step_smote(Post3Meta, over_ratio = 1, neighbors = 3)

```


```{r}
ou_prep <- prep(ou_rec, training = ou_train)
ou_baked <- bake(ou_prep, new_data = NULL)
```


#===========================#
#     OrdinalNet Model      #
#===========================#

```{r}
library("ordinalNet")
library("ordinalgmifs")
```

```{r}
# make sure its ordered factor
y <- ou_baked$Post3Meta
x <- ou_baked %>% 
  dplyr::select(-Post3Meta) %>% as.matrix()

# tune the model
set.seed(123)
fit_tuned <- ordinalNetTune(
  x = x,
  y = y,
  family = "cumulative",   # ordered logit
  link = "logit",
  parallelTerms = TRUE,
  nonparallelTerms = FALSE,
  lambdaMinRatio = 1e-4,   
  nFolds = 10, 
  printProgress = TRUE   
)

summary(fit_tuned)

```


#===========================#
#   Prediction + Evaluation #
#===========================#

```{r}
# remember to bake the test data!!
ou_test  <- bake(ou_prep, new_data = ou_test)

x_test <- ou_test %>% 
  dplyr::select(-Post3Meta) %>%  
  model.matrix(~ . -1, data = .)

# Predict class labels
pred_class <- predict(fit_tuned$fit, newx = x_test, type = "class", 
                      whichLambda = fit_tuned$lambdaOpt)


y_test <- ou_test$Post3Meta

# Ensure pred and truth are both ordered factors with same levels
levs <- levels(y_test)

df_pred <- tibble(
  truth = factor(y_test, levels = levs, ordered = TRUE),
  pred = factor(pred_class, levels = levs, ordered = TRUE)
)

# Accuracy
acc <- yardstick::accuracy(df_pred, truth = truth, estimate = pred)

print(acc)

```


#===========================#
#      QWK   Results        #
#===========================#

```{r}
library(Metrics)

qwk_score <- ScoreQuadraticWeightedKappa(as.integer(y_test), as.integer(pred_class))
print(qwk_score)
```

> print(qwk_score)
[1] 0.3610883


