
```{r}
library(tidyverse)
library(tidymodels)
library(dplyr)
library(janitor)
library(themis)
```

#------------------------------------------------------------
# Training process-------------------------------------------

# adjust paths
```{r}
score <- read_csv('C:/Users/ASUS/Desktop/MATHia/student_scores_train.csv')
feature <- read_csv('C:/Users/ASUS/Desktop/MATHia/features_train.csv')
```

```{r}
ou <- score %>%
  dplyr::select("Anon.Student.Id","PostMotivation3") %>%
  left_join(feature, by = "Anon.Student.Id")
```


#===========================#
#     Data Preprocessing    #
#===========================#

# round + remove NA
```{r}
table(ou$PostMotivation3)

ou$PostMotivation3 <- round(ou$PostMotivation3)

ou <- ou %>% drop_na(PostMotivation3)

table(ou$PostMotivation3)
```

# outcome must be an ordered factor
```{r}
ou$PostMotivation3 <- factor(ou$PostMotivation3,
                             levels = sort(unique(ou$PostMotivation3)),
                             ordered = TRUE)

ou$PostMotivation3
```


#===========================#
#   feature selection       #
#===========================#

```{r}
selected_features <- c(
  "aplse_score_ratio",
  "graduation_rate",
  "Level2_Hints_Per_Problem",
  "avg_jit_per_problem",
  "avg_error_count",
  "avg_skill_mastery_ratio",
  "avg_problem_completion_ratio",
  "avg_attempt_per_problem",
  "correct_attempt_ratio"
)
```


```{r}
ou <- ou %>%
  dplyr::select(Anon.Student.Id, PostMotivation3, all_of(selected_features))
```


# training and testing 

```{r}
ou_train<- ou
```


## Formula and Recipe
```{r}
rf_formula<-as.formula("PostMotivation3 ~ .")
```

```{r}
ou_rec <- recipe(rf_formula, data = ou_train) %>%
  update_role(Anon.Student.Id, new_role = "ID") %>%
  update_role(PostMotivation3, new_role = "outcome") %>%
  step_nzv(all_predictors()) %>%
  step_impute_knn(all_numeric_predictors()) %>%
  step_corr(all_numeric_predictors(), threshold = 0.95) %>%
  step_normalize(all_predictors()) %>%
  step_smote(PostMotivation3, over_ratio = 1, neighbors = 3)

```


```{r}
ou_prep <- prep(ou_rec, training = ou_train)
ou_baked <- bake(ou_prep, new_data = NULL)
```


# Ordinal Net
```{r}
library("ordinalNet")
library("ordinalgmifs")
```

```{r}
# make sure its ordered factor
y <- ou_baked$PostMotivation3
x <- ou_baked %>% 
  dplyr::select(-PostMotivation3, - Anon.Student.Id) %>% as.matrix()

# tune the model
set.seed(123)
fit_tuned <- ordinalNetTune(
  x = x,
  y = y,
  family = "cumulative",   # ordered logit
  link = "logit",
  parallelTerms = TRUE,
  nonparallelTerms = FALSE,
  lambdaMinRatio = 1e-4,  
  nFolds = 10, 
  printProgress = TRUE   
)

summary(fit_tuned)

```


#===========================#
#         Save model        #
#===========================#

```{r}
saveRDS(fit_tuned, file = "C:/Users/ASUS/Desktop/MATHia/Motivation/ordinalnet_fit_tuned_postMotivation3.rds")

saveRDS(ou_rec, file = "C:/Users/ASUS/Desktop/MATHia/Motivation/ordinalnet_recipe_postMotivation3.rds")
```



#----------------TESTING START HERE----------------------
#--------------------------------------------------------

# adjust path
```{r}
fit_tuned <- readRDS("C:/Users/ASUS/Desktop/MATHia/Motivation/ordinalnet_fit_tuned_postMotivation3.rds")
prep_rec <- readRDS("C:/Users/ASUS/Desktop/MATHia/Motivation/ordinalnet_recipe_postMotivation3.rds")
```


# read the testing data
```{r}
feature_test <- read_csv("C:/Users/ASUS/Desktop/MATHia/features_test.csv")  # adjust path
```


#===========================#
#   feature selection       #
#===========================#

```{r}
selected_features <- c(
  "aplse_score_ratio",
  "graduation_rate",
  "num_problem",
  "Level2_Hints_Per_Problem",
  "avg_jit_per_problem",
  "avg_error_count",
  "avg_skill_mastery_ratio",
  "avg_problem_completion_ratio",
  "avg_attempt_per_problem",
  "correct_attempt_ratio"
  #"avg_correct_attempt_per_problem"
)
```


```{r}
ou_test <- feature_test %>% dplyr::select(Anon.Student.Id, all_of(selected_features))
```

#===========================#
#     Predict Test Labels   #
#===========================#

```{r}
library("ordinalNet")
library("ordinalgmifs")
```

# Bake the test data
```{r}
prep_rec <- prep(prep_rec)
ou_test  <- bake(prep_rec, new_data = ou_test)
```


```{r}
# Get the features
x_test <- ou_test %>% 
  dplyr::select(-Anon.Student.Id) %>% 
  model.matrix(~ . -1, data = .)

# Predict class labels
pred_class <- predict(fit_tuned$fit, newx = x_test, type = "class", 
                      whichLambda = fit_tuned$lambdaOpt)

# Combine predictions with the original ID
df_pred <- tibble(
  Anon.Student.Id = ou_test$Anon.Student.Id,   # keep the original ID
  .pred = factor(pred_class, levels = 1:7, ordered = TRUE)  # predicted classes
)
```


#===========================#
#      Output Files         #
#===========================#

```{r}
write.csv(df_pred, "C:/Users/ASUS/Desktop/MATHia/PostMath/PostMotivation3_pred.csv", row.names = FALSE)
```

